# Generated by Django 6.0.5 on 2026-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tab',
            field=models.CharField(choices=[('tab1', 'Top talent outsourcing'), ('tab2', 'Project Management'), ('tab3', 'Digital Transformation')], default='tab1', max_length=10),
        ),
    ]
