# Generated by Django 6.0.7 on 2026-07-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., '16 Hrs' or 'CO2'", max_length=50
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="e.g., 'Non Stop' or 'Carbon Free'", max_length=50
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., 'fa-microchip', 'fa-leaf')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="website.banner",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
