# Generated by Django 6.0.5 on 2026-06-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tab',
            field=models.CharField(choices=[('tab1', 'Okla '), ('tab2', 'YJ Future'), ('tab3', 'Road King')], default='tab1', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
