"""
Django settings for eveebike project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#^isz)u@-$bt4wqu)g2%2*c5$hw21tmj&u$!%-h4kh_@7&((ej'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS - For production, restrict this
ALLOWED_HOSTS = ['*']  # For development only
# For production, use: ALLOWED_HOSTS = ['eveebike.pythonanywhere.com', 'yourdomain.com']

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eveebike.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Add this for development
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Add this for media files
            ],
        },
    },
]

WSGI_APPLICATION = 'eveebike.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'  # Added leading slash
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ADD THIS - Required for collectstatic
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============== EMAIL SETTINGS ===============
# IMPORTANT: Never commit real passwords to version control!
# Use environment variables for production

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # FIXED: Should be smtp.gmail.com, not your email
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'riazusman476@gmail.com'
EMAIL_HOST_PASSWORD = 'USman2213@!'  # ⚠️ Never hardcode passwords! Use environment variables
DEFAULT_FROM_EMAIL = 'riazusman476@gmail.com'
ADMIN_EMAIL = 'admin@yourdomain.com'

# For development, use console backend to avoid sending real emails:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# =============== SITE SETTINGS ===============
SITE_NAME = 'EveeBike'
SITE_URL = 'https://eveebike.com'  # Update with your actual domain


# =============== JAZZMIN SETTINGS ===============
JAZZMIN_SETTINGS = {
    "site_title": "EV Bikes Admin",
    "site_header": "EV Bikes",
    "site_brand": "EV Bikes Admin",
    "welcome_sign": "Welcome to EV Bikes Admin Panel",
    "copyright": "EV Bikes",
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["auth.User", "website.Product"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "website.Banner": "fas fa-image",
        "website.Product": "fas fa-box",
        "website.Cart": "fas fa-shopping-cart",
        "website.CartItem": "fas fa-shopping-basket",
        "website.Order": "fas fa-shopping-bag",
        "website.OrderItem": "fas fa-boxes",
        "website.Testimonial": "fas fa-star",
        "website.Service": "fas fa-cog",
        "website.Project": "fas fa-project-diagram",
        "website.BlogPost": "fas fa-blog",
        "website.SiteSetting": "fas fa-cogs",
    },
    "order_with_respect_to": [
        "website",
        "auth",
    ],
}

# For Django 3.2+ (required)
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']